import {
  BadgePercent,
  Ban,
  BarChart3,
  Bell,
  BellOff,
  Bot,
  Brain,
  Calculator,
  Calendar,
  CalendarClock,
  ListChecks,
  CalendarHeart,
  TrendingUp,
  CalendarDays,
  CalendarX,
  ChartNoAxesColumnDecreasing,
  CheckCheck,
  Cigarette,
  CircleDollarSign,
  CircleSlash,
  ClipboardList,
  Clock,
  Coffee,
  DollarSign,
  Droplets,
  Eye,
  EyeOff,
  FileStack,
  FileText,
  FileX,
  Filter,
  Footprints,
  Frown,
  Gauge,
  Globe,
  Handshake,
  Headphones,
  HeartCrack,
  Hourglass,
  Inbox,
  KeyRound,
  Link,
  ListTodo,
  Lock,
  Mail,
  MailWarning,
  MailX,
  Megaphone,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Moon,
  Palmtree,
  Percent,
  Phone,
  PhoneMissed,
  PhoneOff,
  PieChart,
  Plane,
  Puzzle,
  Radar,
  Receipt,
  ReceiptText,
  Repeat,
  Repeat2,
  Search,
  Send,
  ShieldAlert,
  ShieldCheck,
  ShieldX,
  Siren,
  Skull,
  Smartphone,
  Snail,
  Snowflake,
  Sparkles,
  Star,
  Store,
  Thermometer,
  ThermometerSnowflake,
  ThumbsDown,
  Timer,
  TimerOff,
  TrendingDown,
  Trash2,
  TreePalm,
  Turtle,
  Undo2,
  Unlink,
  UserX,
  Users,
  Voicemail,
  Wand2,
  WandSparkles,
  Webhook,
  Workflow,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import type { MarketApp } from '../../../store/types';

// Безопасная карта «имя иконки → компонент». Импортировать весь набор lucide
// нельзя (это сотни килобайт), поэтому держим список известных имён и запасную иконку.
const ICONS: Record<string, LucideIcon> = {
  BadgePercent,
  Ban,
  BarChart3,
  Bell,
  BellOff,
  Bot,
  Brain,
  Calculator,
  Calendar,
  CalendarClock,
  ListChecks,
  CalendarHeart,
  TrendingUp,
  CalendarDays,
  CalendarX,
  ChartNoAxesColumnDecreasing,
  CheckCheck,
  Cigarette,
  CircleDollarSign,
  CircleSlash,
  ClipboardList,
  Clock,
  Coffee,
  DollarSign,
  Droplets,
  Eye,
  EyeOff,
  FileStack,
  FileText,
  FileX,
  Filter,
  Footprints,
  Frown,
  Gauge,
  Globe,
  Handshake,
  Headphones,
  HeartCrack,
  Hourglass,
  Inbox,
  KeyRound,
  Link,
  ListTodo,
  Lock,
  Mail,
  MailWarning,
  MailX,
  Megaphone,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Moon,
  Palmtree,
  Percent,
  Phone,
  PhoneMissed,
  PhoneOff,
  PieChart,
  Plane,
  Puzzle,
  Radar,
  Receipt,
  ReceiptText,
  Repeat,
  Repeat2,
  Search,
  Send,
  ShieldAlert,
  ShieldCheck,
  ShieldX,
  Siren,
  Skull,
  Smartphone,
  Snail,
  Snowflake,
  Sparkles,
  Star,
  Store,
  Thermometer,
  ThermometerSnowflake,
  ThumbsDown,
  Timer,
  TimerOff,
  TrendingDown,
  Trash2,
  TreePalm,
  Turtle,
  Undo2,
  Unlink,
  UserX,
  Users,
  Voicemail,
  Wand2,
  WandSparkles,
  Webhook,
  Workflow,
  Zap,
};

export function iconByName(name?: string, fallback: LucideIcon = Puzzle): LucideIcon {
  return (name && ICONS[name]) || fallback;
}

/** Светлый ли цвет: тогда иконку рисуем тёмной */
export function isLight(hex: string) {
  const m = /^#?([0-9a-f]{3}|[0-9a-f]{6})$/i.exec(hex.trim());
  if (!m) return false;
  let h = m[1];
  if (h.length === 3) h = h.replace(/./g, (c) => c + c);
  const n = parseInt(h, 16);
  const r = (n >> 16) & 255;
  const g = (n >> 8) & 255;
  const b = n & 255;
  return (0.299 * r + 0.587 * g + 0.114 * b) / 255 > 0.68;
}

export function AppLogo({ app, size = 64 }: { app: Pick<MarketApp, 'color' | 'icon' | 'name'>; size?: number }) {
  const Icon = iconByName(app.icon);
  const color = app.color || '#2f80ed';
  return (
    <span
      className="mkt-logo"
      style={{
        width: size,
        height: size,
        borderRadius: Math.round(size * 0.22),
        background: color,
        color: isLight(color) ? '#1d2f40' : '#fff',
      }}
      aria-hidden="true"
    >
      <Icon size={Math.round(size * 0.48)} strokeWidth={1.7} />
    </span>
  );
}
